import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api/client";
import { requestAdminStepUp } from "../api/adminStepUp";

type Review = { _id: string; rating: number; comment: string; moderationStatus: "active" | "hidden"; createdAt: string; reviewer?: { displayName?: string }; seller?: { displayName?: string }; listing?: { title?: string } };
export default function AdminReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [status, setStatus] = useState("active"); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await apiClient.get<{ data: { reviews: Review[] }; meta?: { totalPages: number } }>("/admin/reviews", { params: { status, page, limit: 20 } }); setReviews(data.data.reviews); setPages(data.meta?.totalPages ?? 1); } catch { setError("Could not load reviews."); } finally { setLoading(false); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function toggle(review: Review, next: "active" | "hidden") { if (!window.confirm(`${next === "hidden" ? "Hide" : "Restore"} this review?`)) return; try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/reviews/${review._id}/status`, { status: next }); await load(); } catch { setError("Could not update review moderation status."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold tracking-tight text-campus-ink">Review moderation</h1><p className="mt-2 text-sm text-campus-muted">Hide or restore a review. Hidden reviews are excluded from vendor ratings.</p></div><select className="rounded-lg border border-campus-line bg-white px-3 py-2 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="active">Public</option><option value="hidden">Hidden</option></select></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-3">{reviews.map((review) => <article key={review._id} className="rounded-xl border border-campus-line bg-campus-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-[10px] font-extrabold uppercase tracking-wide text-campus-accent">{review.moderationStatus} · {"★".repeat(review.rating)}</span><p className="mt-1 text-sm">{review.comment}</p><p className="mt-2 text-xs text-campus-muted">{review.reviewer?.displayName ?? "Member"} → {review.seller?.displayName ?? "Vendor"}{review.listing?.title ? ` · ${review.listing.title}` : ""} · {new Date(review.createdAt).toLocaleDateString("en-ZA")}</p></div>{review.moderationStatus === "hidden" ? <button onClick={() => void toggle(review, "active")} className="h-fit rounded-md border border-campus-line px-3 py-2 text-xs font-semibold">Restore</button> : <button onClick={() => void toggle(review, "hidden")} className="h-fit rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Hide</button>}</div></article>)}{loading && <p className="p-6 text-center text-campus-muted">Loading reviews…</p>}{!loading && !reviews.length && <p className="rounded-xl border border-campus-line bg-campus-surface p-6 text-center text-sm text-campus-muted">No reviews in this view.</p>}<div className="flex items-center justify-between"><span className="text-[11px] text-campus-muted">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Previous</button><button disabled={page >= pages || loading} onClick={() => setPage(page + 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Next</button></div></div></div></section>;
}
