import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api/client";
import { requestAdminStepUp } from "../api/adminStepUp";

type Health = { status: string; database: string; uptimeSeconds: number; nodeVersion: string; memoryBytes: { rss: number; heapUsed: number; heapTotal: number }; checkedAt: string };
type AlertItem = { type: string; severity: "high" | "medium"; target: string; count: number; subject: string; message: string; amountCents?: number; createdAt?: string };
type Promotion = { _id: string; title: string; category: string; priceCents: number; discountPercent: number; seller?: { displayName?: string } };
const money = (cents: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(cents / 100);

export function AdminHealthPage() {
  const [health, setHealth] = useState<Health | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const { data } = await apiClient.get<{ data: Health }>("/admin/health"); setHealth(data.data); } catch { setError("Could not read system health."); } }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, [load]);
  const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">System health</h1><p className="mb-5 text-sm text-campus-muted">Backend process and database status. Refreshes every 30 seconds.</p>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{!health && !error && <p className="text-sm text-campus-muted">Loading health…</p>}{health && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["API status", health.status], ["Database", health.database], ["Uptime", `${Math.floor(health.uptimeSeconds / 3600)}h ${Math.floor(health.uptimeSeconds % 3600 / 60)}m`], ["Node.js", health.nodeVersion], ["Memory in use", mb(health.memoryBytes.rss)], ["Heap used", mb(health.memoryBytes.heapUsed)], ["Heap allocated", mb(health.memoryBytes.heapTotal)], ["Checked", new Date(health.checkedAt).toLocaleTimeString("en-ZA")]].map(([label, value]) => <article key={label} className="rounded-xl border border-campus-line bg-campus-surface p-5"><span className="text-xs font-semibold text-campus-muted">{label}</span><strong className="mt-3 block text-xl capitalize text-campus-ink">{value}</strong></article>)}</div><p className="mt-4 text-xs text-campus-muted">This is process-level health information, not a full infrastructure monitoring service.</p></>}</section>;
}

export function AdminFraudPage() {
  const [alerts, setAlerts] = useState<AlertItem[]>([]); const [generatedAt, setGeneratedAt] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const { data } = await apiClient.get<{ data: { alerts: AlertItem[]; generatedAt: string } }>("/admin/fraud-alerts"); setAlerts(data.data.alerts); setGeneratedAt(data.data.generatedAt); setError(""); } catch { setError("Could not load risk alerts."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold tracking-tight text-campus-ink">Fraud alerts</h1><p className="mt-2 text-sm text-campus-muted">Heuristic signals for human review; these are not automated fraud determinations.</p></div><button onClick={() => void load()} className="rounded-lg border border-campus-line bg-white px-4 py-2 text-sm font-semibold">Refresh</button></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{alerts.map((alert, index) => <article key={`${alert.type}-${alert.target}-${index}`} className="mb-3 rounded-xl border border-campus-line bg-campus-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`text-[10px] font-extrabold uppercase ${alert.severity === "high" ? "text-red-700" : "text-orange-700"}`}>{alert.severity} · {alert.type.replace(/_/g, " ")}</span><h2 className="mt-1 font-bold">{alert.subject}</h2><p className="mt-2 text-sm text-campus-muted">{alert.message}</p></div><span className="rounded-full bg-campus-background px-3 py-1 text-xs">{alert.count} signal{alert.count === 1 ? "" : "s"}</span></div>{alert.amountCents != null && <p className="mt-3 text-sm font-semibold">Refunded total: {money(alert.amountCents)}</p>}</article>)}{loading && <p className="p-6 text-center text-campus-muted">Checking risk rules…</p>}{!loading && !alerts.length && !error && <p className="rounded-xl border border-campus-line bg-campus-surface p-6 text-center text-sm text-campus-muted">No current signals matched the review rules.</p>}<p className="mt-4 text-[11px] text-campus-muted">Generated {generatedAt ? new Date(generatedAt).toLocaleString("en-ZA") : "—"}. Rules currently flag repeated open reports and unusually frequent/high-value refunds.</p></section>;
}

export function AdminPromotionsPage() {
  const [items, setItems] = useState<Promotion[]>([]); const [values, setValues] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const { data } = await apiClient.get<{ data: { promotions: Promotion[] } }>("/admin/promotions"); setItems(data.data.promotions); setValues(Object.fromEntries(data.data.promotions.map((item) => [item._id, String(item.discountPercent)]))); } catch { setError("Could not load promotions."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(item: Promotion) { const discountPercent = Number(values[item._id]); if (!Number.isInteger(discountPercent) || discountPercent < 0 || discountPercent > 90) { setError("Discount must be a whole number from 0 to 90."); return; } try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/promotions/${item._id}`, { discountPercent }); await load(); } catch { setError("Could not update promotion."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">Promotions</h1><p className="mb-5 text-sm text-campus-muted">Review active listing discounts and update a promotion rate.</p>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl border border-campus-line bg-campus-surface"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-campus-background text-campus-muted"><tr>{["Listing", "Vendor", "Regular price", "Discount", "Sale price", "Action"].map((label) => <th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{items.map((item) => { const discount = Number(values[item._id] ?? 0); return <tr key={item._id} className="border-t border-campus-line"><td className="px-4 py-3"><strong>{item.title}</strong><span className="mt-1 block capitalize text-campus-muted">{item.category}</span></td><td className="px-4 py-3">{item.seller?.displayName ?? "Vendor"}</td><td className="px-4 py-3">{money(item.priceCents)}</td><td className="px-4 py-3"><input aria-label={`Discount for ${item.title}`} className="w-20 rounded-md border border-campus-line px-2 py-1.5" type="number" min="0" max="90" step="1" value={values[item._id] ?? "0"} onChange={(e) => setValues((current) => ({ ...current, [item._id]: e.target.value }))} />%</td><td className="px-4 py-3 font-semibold">{money(Math.round(item.priceCents * (100 - Math.min(90, Math.max(0, discount))) / 100))}</td><td className="px-4 py-3"><button onClick={() => void save(item)} className="rounded-md bg-campus-accent px-3 py-2 font-bold text-white">Save</button></td></tr>; })}</tbody></table>{loading && <p className="p-6 text-center text-campus-muted">Loading promotions…</p>}{!loading && !items.length && <p className="p-6 text-center text-campus-muted">No active discounted listings.</p>}</div></section>;
}
