import { useCallback, useEffect, useState, type FormEvent } from "react";
import { apiClient } from "../api/client";
import { requestAdminStepUp } from "../api/adminStepUp";

type Institution = { _id: string; name: string; domains: string[]; active: boolean };
type Poll = { _id: string; question: string; description?: string; options: string[]; voteCounts?: number[]; totalVotes?: number; status: "draft" | "open" | "closed"; startsAt?: string; endsAt?: string };

export function AdminInstitutionsPage() {
  const [institutions, setInstitutions] = useState<Institution[]>([]); const [name, setName] = useState(""); const [domains, setDomains] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const { data } = await apiClient.get<{ data: { institutions: Institution[] } }>("/admin/institutions"); setInstitutions(data.data.institutions); } catch { setError("Could not load institutions."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); setError(""); try { if (!(await requestAdminStepUp())) return; await apiClient.post("/admin/institutions", { name, domains: domains.split(/[\n,]/).map((domain) => domain.trim().toLowerCase()).filter(Boolean), active: true }); setName(""); setDomains(""); await load(); } catch { setError("Could not create institution. Check that its name and domains are unique and valid."); } }
  async function toggle(item: Institution) { try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/institutions/${item._id}`, { active: !item.active }); await load(); } catch { setError("Could not update institution status."); } }
  async function edit(item: Institution) { const nextName = window.prompt("Institution name", item.name); if (!nextName?.trim()) return; const nextDomains = window.prompt("Email domains (comma separated)", item.domains.join(", ")); if (nextDomains === null) return; try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/institutions/${item._id}`, { name: nextName.trim(), domains: nextDomains.split(",").map((domain) => domain.trim().toLowerCase()).filter(Boolean) }); await load(); } catch { setError("Could not update institution."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">Institutions</h1><p className="mb-5 text-sm text-campus-muted">Manage institutions and the email domains used for campus verification.</p>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<form onSubmit={save} className="mb-5 grid gap-3 rounded-xl border border-campus-line bg-campus-surface p-5 md:grid-cols-[1fr_1fr_auto]"><input required minLength={2} maxLength={160} className="rounded-lg border border-campus-line px-3 py-2 text-sm" placeholder="Institution name" value={name} onChange={(e) => setName(e.target.value)} /><textarea required className="rounded-lg border border-campus-line px-3 py-2 text-sm" placeholder="Email domains (one per line or comma separated)" value={domains} onChange={(e) => setDomains(e.target.value)} /><button className="rounded-lg bg-campus-accent px-4 py-2 text-sm font-bold text-white">Add institution</button></form><div className="overflow-x-auto rounded-xl border border-campus-line bg-campus-surface"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-campus-background text-campus-muted"><tr>{["Institution", "Allowed domains", "Status", "Actions"].map((label) => <th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{institutions.map((item) => <tr key={item._id} className="border-t border-campus-line"><td className="px-4 py-3 font-semibold">{item.name}</td><td className="px-4 py-3">{item.domains.join(", ") || "—"}</td><td className="px-4 py-3">{item.active ? "Active" : "Inactive"}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => void edit(item)} className="rounded-md border border-campus-line px-3 py-2 font-semibold">Edit</button><button onClick={() => void toggle(item)} className="rounded-md border border-campus-line px-3 py-2 font-semibold">{item.active ? "Deactivate" : "Activate"}</button></div></td></tr>)}</tbody></table>{loading && <p className="p-6 text-center text-campus-muted">Loading institutions…</p>}{!loading && !institutions.length && <p className="p-6 text-center text-campus-muted">No institutions configured.</p>}</div></section>;
}

export function AdminPollsPage() {
  const [polls, setPolls] = useState<Poll[]>([]); const [question, setQuestion] = useState(""); const [optionsText, setOptionsText] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const { data } = await apiClient.get<{ data: { polls: Poll[] } }>("/admin/polls"); setPolls(data.data.polls); } catch { setError("Could not load polls."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); setError(""); try { if (!(await requestAdminStepUp())) return; await apiClient.post("/admin/polls", { question, options: optionsText.split("\n").map((option) => option.trim()).filter(Boolean), status: "draft" }); setQuestion(""); setOptionsText(""); await load(); } catch { setError("Could not create poll. Add a question and at least two unique options."); } }
  async function changeStatus(poll: Poll, status: Poll["status"]) { try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/polls/${poll._id}`, { status }); await load(); } catch { setError("Could not update poll status."); } }
  async function remove(poll: Poll) { if (!window.confirm(`Delete the poll “${poll.question}”?`)) return; try { if (!(await requestAdminStepUp())) return; await apiClient.delete(`/admin/polls/${poll._id}`); await load(); } catch { setError("Could not delete poll."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">Polls & surveys</h1><p className="mb-5 text-sm text-campus-muted">Create polls, set availability, and review live vote totals.</p>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<form onSubmit={create} className="mb-5 grid gap-3 rounded-xl border border-campus-line bg-campus-surface p-5"><input required minLength={5} maxLength={240} className="rounded-lg border border-campus-line px-3 py-2 text-sm" placeholder="Poll question" value={question} onChange={(e) => setQuestion(e.target.value)} /><textarea required className="rounded-lg border border-campus-line px-3 py-2 text-sm" placeholder="Options (one per line; 2 to 10)" value={optionsText} onChange={(e) => setOptionsText(e.target.value)} /><button className="w-fit rounded-lg bg-campus-accent px-4 py-2 text-sm font-bold text-white">Create draft poll</button></form><div className="grid gap-3">{polls.map((poll) => <article key={poll._id} className="flex flex-wrap items-start justify-between gap-4 rounded-xl border border-campus-line bg-campus-surface p-5"><div><span className="text-[10px] font-extrabold uppercase tracking-wide text-campus-accent">{poll.status} · {poll.totalVotes ?? 0} votes</span><h2 className="mt-1 font-bold">{poll.question}</h2><ul className="mt-2 space-y-1 text-sm text-campus-muted">{poll.options.map((option, index) => <li key={option} className="flex justify-between gap-5"><span>{option}</span><span className="font-semibold text-campus-ink">{poll.voteCounts?.[index] ?? 0}</span></li>)}</ul></div><div className="flex flex-wrap gap-2"><select className="rounded-md border border-campus-line px-3 py-2 text-xs" value={poll.status} onChange={(e) => void changeStatus(poll, e.target.value as Poll["status"])}><option value="draft">Draft</option><option value="open">Open</option><option value="closed">Closed</option></select><button onClick={() => void remove(poll)} className="rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Delete</button></div></article>)}{loading && <p className="p-6 text-center text-campus-muted">Loading polls…</p>}{!loading && !polls.length && <p className="rounded-xl border border-campus-line bg-campus-surface p-6 text-center text-sm text-campus-muted">No polls created.</p>}</div></section>;
}
