import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api/client";

type AuditLog = { _id: string; action: string; targetType: string; targetId: string; metadata: Record<string, unknown>; ipAddress?: string; createdAt: string; actor?: { displayName?: string; email?: string } };
export default function AdminAuditPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await apiClient.get<{ data: { logs: AuditLog[] }; meta?: { totalPages: number } }>("/admin/audit", { params: { page, limit: 30 } }); setLogs(data.data.logs); setPages(data.meta?.totalPages ?? 1); } catch { setError("Could not load the audit log."); } finally { setLoading(false); } }, [page]);
  useEffect(() => { void load(); }, [load]);
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">Audit log</h1><p className="mb-5 text-sm text-campus-muted">Read-only history of sensitive administrator actions.</p>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="overflow-hidden rounded-xl border border-campus-line bg-campus-surface">{logs.map((log) => <article key={log._id} className="grid gap-2 border-b border-campus-line px-5 py-4 sm:grid-cols-[1fr_auto]"><div><strong className="text-sm">{log.action}</strong><p className="mt-1 text-xs text-campus-muted">{log.actor?.displayName ?? log.actor?.email ?? "Administrator"} · {log.targetType} · {log.targetId}</p>{Object.keys(log.metadata ?? {}).length > 0 && <pre className="mt-2 overflow-auto rounded-lg bg-campus-background p-2 text-[10px] text-campus-muted">{JSON.stringify(log.metadata)}</pre>}</div><time className="text-xs text-campus-muted">{new Date(log.createdAt).toLocaleString("en-ZA")}<span className="mt-1 block">{log.ipAddress ?? ""}</span></time></article>)}{loading && <p className="p-6 text-center text-campus-muted">Loading audit log…</p>}{!loading && !logs.length && <p className="p-6 text-center text-campus-muted">No administrator actions recorded yet.</p>}<div className="flex items-center justify-between px-4 py-3"><span className="text-[11px] text-campus-muted">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Previous</button><button disabled={page >= pages || loading} onClick={() => setPage(page + 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Next</button></div></div></div></section>;
}
