import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api/client";
import { requestAdminStepUp } from "../api/adminStepUp";

type Post = { _id: string; title: string; summary: string; body: string; type: string; moderationStatus: "active" | "hidden"; createdAt: string; author?: { displayName?: string; email?: string } };
export default function AdminCommunityPage() {
  const [posts, setPosts] = useState<Post[]>([]); const [status, setStatus] = useState("active"); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await apiClient.get<{ data: { posts: Post[] }; meta?: { totalPages: number } }>("/admin/community-posts", { params: { status, page, limit: 20 } }); setPosts(data.data.posts); setPages(data.meta?.totalPages ?? 1); } catch { setError("Could not load community posts."); } finally { setLoading(false); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function setPostStatus(post: Post, next: "active" | "hidden") { if (!window.confirm(`${next === "hidden" ? "Hide" : "Restore"} “${post.title}”?`)) return; try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/community-posts/${post._id}/status`, { status: next }); await load(); } catch { setError("Could not update post moderation status."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold tracking-tight text-campus-ink">Community post moderation</h1><p className="mt-2 text-sm text-campus-muted">Hide or restore bulletin posts while preserving their history.</p></div><select className="rounded-lg border border-campus-line bg-white px-3 py-2 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="active">Public</option><option value="hidden">Hidden</option></select></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-3">{posts.map((post) => <article key={post._id} className="rounded-xl border border-campus-line bg-campus-surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-[10px] font-extrabold uppercase tracking-wide text-campus-accent">{post.type} · {post.moderationStatus}</span><h2 className="mt-1 font-bold">{post.title}</h2><p className="mt-1 text-xs text-campus-muted">By {post.author?.displayName ?? post.author?.email ?? "Member"} · {new Date(post.createdAt).toLocaleDateString("en-ZA")}</p></div>{post.moderationStatus === "hidden" ? <button onClick={() => void setPostStatus(post, "active")} className="h-fit rounded-md border border-campus-line px-3 py-2 text-xs font-semibold">Restore post</button> : <button onClick={() => void setPostStatus(post, "hidden")} className="h-fit rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Hide post</button>}</div><p className="mt-3 text-sm text-campus-muted">{post.summary}</p><details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold">Read full post</summary><p className="mt-2 whitespace-pre-wrap leading-5">{post.body}</p></details></article>)}{loading && <p className="p-6 text-center text-campus-muted">Loading community posts…</p>}{!loading && !posts.length && <p className="rounded-xl border border-campus-line bg-campus-surface p-6 text-center text-sm text-campus-muted">No posts in this queue.</p>}<div className="flex items-center justify-between"><span className="text-[11px] text-campus-muted">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Previous</button><button disabled={page >= pages || loading} onClick={() => setPage(page + 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Next</button></div></div></div></section>;
}
