import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api/client";
import { requestAdminStepUp } from "../api/adminStepUp";

type Listing = { _id: string; title: string; category: string; status: "active" | "sold" | "draft"; priceCents: number; seller?: { displayName?: string; email?: string } };
type Report = { _id: string; reason: string; details?: string; status: "open" | "reviewed" | "dismissed"; createdAt: string; reporter?: { displayName?: string; email?: string }; listing?: { title?: string; status?: string }; seller?: { displayName?: string; email?: string } };
const money = (cents: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(cents / 100);

export function AdminListingsPage() {
  const [items, setItems] = useState<Listing[]>([]); const [q, setQ] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await apiClient.get<{ data: { listings: Listing[] }; meta?: { totalPages: number } }>("/admin/listings", { params: { q: search || undefined, status: status || undefined, page, limit: 20 } }); setItems(data.data.listings); setPages(data.meta?.totalPages ?? 1); } catch { setError("Could not load listings."); } finally { setLoading(false); } }, [page, search, status]);
  useEffect(() => { void load(); }, [load]);
  async function setListingStatus(item: Listing, next: "active" | "draft") { if (!window.confirm(`${next === "draft" ? "Hide" : "Restore"} “${item.title}”?`)) return; try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/listings/${item._id}/status`, { status: next }); await load(); } catch { setError("Could not update listing status."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><h1 className="mb-2 text-3xl font-extrabold tracking-tight text-campus-ink">Listing moderation</h1><p className="mb-5 text-sm text-campus-muted">Search listings and hide or restore them in the marketplace.</p>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mb-4 flex flex-wrap gap-2"><form className="flex min-w-[220px] flex-1 gap-2" onSubmit={(e) => { e.preventDefault(); setPage(1); setSearch(q.trim()); }}><input className="min-w-0 flex-1 rounded-lg border border-campus-line bg-white px-3 py-2 text-sm" placeholder="Search title or category" value={q} onChange={(e) => setQ(e.target.value)} /><button className="rounded-lg bg-campus-accent px-4 py-2 text-sm font-bold text-white">Search</button></form><select className="rounded-lg border border-campus-line bg-white px-3 py-2 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option><option value="active">Active</option><option value="draft">Hidden / draft</option><option value="sold">Sold</option></select></div><div className="overflow-x-auto rounded-xl border border-campus-line bg-campus-surface"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-campus-background text-campus-muted"><tr>{["Listing", "Seller", "Price", "Status", "Actions"].map((label) => <th key={label} className="px-4 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item._id} className="border-t border-campus-line"><td className="px-4 py-3"><strong>{item.title}</strong><span className="mt-1 block capitalize text-campus-muted">{item.category}</span></td><td className="px-4 py-3">{item.seller?.displayName ?? item.seller?.email ?? "Seller"}</td><td className="px-4 py-3">{money(item.priceCents)}</td><td className="px-4 py-3 capitalize">{item.status}</td><td className="px-4 py-3">{item.status === "active" ? <button onClick={() => void setListingStatus(item, "draft")} className="rounded-md border border-red-200 px-3 py-2 font-semibold text-red-700">Hide listing</button> : item.status === "draft" ? <button onClick={() => void setListingStatus(item, "active")} className="rounded-md border border-campus-line px-3 py-2 font-semibold">Restore</button> : <span className="text-campus-muted">No action</span>}</td></tr>)}</tbody></table>{loading && <p className="p-6 text-center text-campus-muted">Loading listings…</p>}{!loading && !items.length && <p className="p-6 text-center text-campus-muted">No listings found.</p>}<Pager page={page} pages={pages} disabled={loading} onChange={setPage} /></div></section>;
}

export function AdminReportsPage() {
  const [items, setItems] = useState<Report[]>([]); const [status, setStatus] = useState("open"); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await apiClient.get<{ data: { reports: Report[] }; meta?: { totalPages: number } }>("/admin/reports", { params: { status, page, limit: 20 } }); setItems(data.data.reports); setPages(data.meta?.totalPages ?? 1); } catch { setError("Could not load reports."); } finally { setLoading(false); } }, [page, status]);
  useEffect(() => { void load(); }, [load]);
  async function resolve(report: Report, next: "reviewed" | "dismissed") { try { if (!(await requestAdminStepUp())) return; await apiClient.patch(`/admin/reports/${report._id}/status`, { status: next }); await load(); } catch { setError("Could not update report."); } }
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">ADMIN WORKSPACE</p><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold tracking-tight text-campus-ink">Reports & moderation</h1><p className="mt-2 text-sm text-campus-muted">Review member reports about listings and sellers.</p></div><select className="rounded-lg border border-campus-line bg-white px-3 py-2 text-sm" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="open">Open</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option></select></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="grid gap-3">{items.map((item) => <article key={item._id} className="rounded-xl border border-campus-line bg-campus-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-extrabold uppercase tracking-wide text-campus-accent">{item.status}</span><h2 className="mt-1 font-bold">{item.reason}</h2><p className="mt-1 text-xs text-campus-muted">Reported by {item.reporter?.displayName ?? "Member"} · {new Date(item.createdAt).toLocaleDateString("en-ZA")}</p></div>{item.status === "open" && <div className="flex gap-2"><button onClick={() => void resolve(item, "reviewed")} className="rounded-md border border-campus-line px-3 py-2 text-xs font-semibold">Mark reviewed</button><button onClick={() => void resolve(item, "dismissed")} className="rounded-md border border-campus-line px-3 py-2 text-xs font-semibold">Dismiss</button></div>}</div><p className="mt-3 text-sm text-campus-ink">{item.details || "No extra details provided."}</p><p className="mt-2 text-xs text-campus-muted">Target: {item.listing ? `Listing — ${item.listing.title ?? "Untitled"} (${item.listing.status ?? "unknown"})` : `Seller — ${item.seller?.displayName ?? item.seller?.email ?? "Unknown"}`}</p></article>)}{loading && <p className="p-6 text-center text-campus-muted">Loading reports…</p>}{!loading && !items.length && <p className="rounded-xl border border-campus-line bg-campus-surface p-6 text-center text-sm text-campus-muted">No reports in this status.</p>}<Pager page={page} pages={pages} disabled={loading} onChange={setPage} /></div></section>;
}

function Pager({ page, pages, disabled, onChange }: { page: number; pages: number; disabled: boolean; onChange: (page: number) => void }) {
  return <div className="flex items-center justify-between border-t border-campus-line px-4 py-3"><span className="text-[11px] text-campus-muted">Page {page} of {pages}</span><div className="flex gap-2"><button disabled={page <= 1 || disabled} onClick={() => onChange(page - 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Previous</button><button disabled={page >= pages || disabled} onClick={() => onChange(page + 1)} className="rounded-lg border border-campus-line px-3 py-2 text-xs disabled:opacity-40">Next</button></div></div>;
}
