import { useEffect, useState } from "react";
import { apiClient } from "../api/client";

type Earning = { _id: string; amountCents: number; refundedAmountCents: number; netCents: number; currency: string; status: string; paymentStatus: string; paymentMethod: string; receiptNumber?: string; createdAt: string };
type Data = { earnings: Earning[]; totals: { grossCents: number; refundedCents: number; netCents: number } };
const money = (cents: number) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR" }).format(cents / 100);

export default function VendorEarningsPage() {
  const [data, setData] = useState<Data | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { apiClient.get("/vendor/earnings").then(({ data: response }) => setData(response.data)).catch(() => setError("Could not load earnings.")); }, []);
  return <section className="mx-auto w-full max-w-[1180px] px-4 py-8 sm:px-6 lg:px-9"><p className="mb-2 text-[10px] font-extrabold tracking-[1.1px] text-campus-accent">VENDOR PORTAL</p><h1 className="mb-6 text-3xl font-extrabold tracking-tight text-campus-ink">Earnings</h1>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{data ? <><div className="mb-6 grid gap-4 sm:grid-cols-3">{[["Gross sales", data.totals.grossCents], ["Refunds", data.totals.refundedCents], ["Net earnings", data.totals.netCents]].map(([label, amount]) => <div key={label} className="rounded-2xl border border-campus-border bg-white p-5 shadow-sm"><p className="text-sm text-campus-muted">{label}</p><p className="mt-2 text-2xl font-extrabold">{money(Number(amount))}</p></div>)}</div><div className="overflow-x-auto rounded-2xl border border-campus-border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-campus-background text-xs uppercase text-campus-muted"><tr>{["Date", "Receipt", "Method", "Order status", "Gross", "Refunded", "Net"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-campus-border">{data.earnings.map((row) => <tr key={row._id}><td className="px-4 py-3">{new Date(row.createdAt).toLocaleDateString()}</td><td className="px-4 py-3">{row.receiptNumber ?? "—"}</td><td className="px-4 py-3 capitalize">{row.paymentMethod}</td><td className="px-4 py-3 capitalize">{row.status}</td><td className="px-4 py-3">{money(row.amountCents)}</td><td className="px-4 py-3">{money(row.refundedAmountCents)}</td><td className="px-4 py-3 font-bold">{money(row.netCents)}</td></tr>)}</tbody></table>{!data.earnings.length && <p className="p-6 text-center text-campus-muted">No paid orders yet.</p>}</div></> : !error && <p className="text-sm text-campus-muted">Loading earnings…</p>}</section>;
}
