import { Router } from "express";
import { createAdminInstitution, createAdminPoll, deleteAdminPoll, deleteAdminUser, getAdminFraudAlerts, getAdminHealth, getAdminOverview, getAdminSettingsSummary, listAdminAuditLogs, listAdminCommunityPosts, listAdminInstitutions, listAdminListings, listAdminPolls, listAdminPromotions, listAdminReports, listAdminReviews, listAdminUsers, listAdminVendors, setAdminCommunityPostStatus, setAdminListingStatus, setAdminReviewStatus, setAdminUserStatus, updateAdminInstitution, updateAdminPoll, updateAdminPromotion, updateAdminReport, updateUserVerification } from "../controllers/adminController";
import { authenticate, requireRoles, requireStepUp } from "../middleware/auth";
import { validate } from "../middleware/validate";
import { listAdminOrders, refundAdminEscrow, refundAdminOrder, releaseAdminEscrow } from "../controllers/adminOrderController";
import { adminAuditQuerySchema, adminCommunityPostQuerySchema, adminCommunityPostStatusSchema, adminInstitutionSchema, adminInstitutionUpdateSchema, adminListingListQuerySchema, adminListingStatusSchema, adminOrderListQuerySchema, adminPollSchema, adminPollUpdateSchema, adminPromotionSchema, adminRefundSchema, adminReportListQuerySchema, adminReportStatusSchema, adminReviewQuerySchema, adminReviewStatusSchema, adminUserListQuerySchema, adminUserStatusSchema, adminVendorListQuerySchema, verificationUpdateSchema } from "../validators/adminValidators";
import { mongoIdParamSchema } from "../validators/commonValidators";

export const adminRouter = Router();

adminRouter.use(authenticate, requireRoles("admin"));
adminRouter.get("/dashboard/overview", getAdminOverview);
adminRouter.get("/users", validate({ query: adminUserListQuerySchema }), listAdminUsers);
adminRouter.get("/vendors", validate({ query: adminVendorListQuerySchema }), listAdminVendors);
adminRouter.get("/listings", validate({ query: adminListingListQuerySchema }), listAdminListings);
adminRouter.patch("/listings/:id/status", requireStepUp, validate({ params: mongoIdParamSchema, body: adminListingStatusSchema }), setAdminListingStatus);
adminRouter.get("/reports", validate({ query: adminReportListQuerySchema }), listAdminReports);
adminRouter.patch("/reports/:id/status", requireStepUp, validate({ params: mongoIdParamSchema, body: adminReportStatusSchema }), updateAdminReport);
adminRouter.get("/orders", validate({ query: adminOrderListQuerySchema }), listAdminOrders);
adminRouter.get("/audit", validate({ query: adminAuditQuerySchema }), listAdminAuditLogs);
adminRouter.get("/community-posts", validate({ query: adminCommunityPostQuerySchema }), listAdminCommunityPosts);
adminRouter.patch("/community-posts/:id/status", requireStepUp, validate({ params: mongoIdParamSchema, body: adminCommunityPostStatusSchema }), setAdminCommunityPostStatus);
adminRouter.get("/institutions", listAdminInstitutions);
adminRouter.post("/institutions", requireStepUp, validate({ body: adminInstitutionSchema }), createAdminInstitution);
adminRouter.patch("/institutions/:id", requireStepUp, validate({ params: mongoIdParamSchema, body: adminInstitutionUpdateSchema }), updateAdminInstitution);
adminRouter.get("/polls", listAdminPolls);
adminRouter.post("/polls", requireStepUp, validate({ body: adminPollSchema }), createAdminPoll);
adminRouter.patch("/polls/:id", requireStepUp, validate({ params: mongoIdParamSchema, body: adminPollUpdateSchema }), updateAdminPoll);
adminRouter.delete("/polls/:id", requireStepUp, validate({ params: mongoIdParamSchema }), deleteAdminPoll);
adminRouter.get("/health", getAdminHealth);
adminRouter.get("/fraud-alerts", getAdminFraudAlerts);
adminRouter.get("/promotions", listAdminPromotions);
adminRouter.patch("/promotions/:id", requireStepUp, validate({ params: mongoIdParamSchema, body: adminPromotionSchema }), updateAdminPromotion);
adminRouter.get("/reviews", validate({ query: adminReviewQuerySchema }), listAdminReviews);
adminRouter.patch("/reviews/:id/status", requireStepUp, validate({ params: mongoIdParamSchema, body: adminReviewStatusSchema }), setAdminReviewStatus);
adminRouter.get("/settings", getAdminSettingsSummary);
adminRouter.post("/orders/:id/refund", requireStepUp, validate({ params: mongoIdParamSchema, body: adminRefundSchema }), refundAdminOrder);
adminRouter.post("/orders/:id/escrow/release", requireStepUp, validate({ params: mongoIdParamSchema }), releaseAdminEscrow);
adminRouter.post("/orders/:id/escrow/refund", requireStepUp, validate({ params: mongoIdParamSchema, body: adminRefundSchema }), refundAdminEscrow);
adminRouter.patch("/users/:id/status", requireStepUp, validate({ params: mongoIdParamSchema, body: adminUserStatusSchema }), setAdminUserStatus);
adminRouter.delete("/users/:id", requireStepUp, validate({ params: mongoIdParamSchema }), deleteAdminUser);
adminRouter.patch("/users/:id/verification", requireStepUp, validate({ params: mongoIdParamSchema, body: verificationUpdateSchema }), updateUserVerification);
